---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart prometheus exporter
  ansible.builtin.systemd:
    name: "{{ prometheus_exporter_service_name }}"
    state: restarted
  when: prometheus_exporter_service_state == 'started'
